name: build-docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: |-
        docker build \
          --tag embed:latest \
          --build-arg="RUST_BINARY=server" \
          .
    # - name: docker run
    #   run: docker run embed:$(date +%s)
    - name: docker run
      run: docker run embed:latest
