name: test-rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: install libtorch
      run: |-
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip -O libtorch.zip
        unzip -o libtorch.zip
        sudo /sbin/ldconfig -v
        echo "LIBTORCH=/libtorch" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

    - name: Linting
      run: cargo clippy -- -D warnings

    - name: Build 
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage
      run: cargo tarpaulin --verbose --workspace


  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Enforce formatting
        run: cargo fmt --check
