# Runs helmfile lint to check for valid helm config.
name: test-helm

on:
  push:
    branches: [ "main" ]
    paths:
      - "deploy/helm/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "deploy/helm/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install helm
      run: |-
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt -y update && sudo apt -y install helm

    - name: install helmfile
      run: |-
        wget "https://github.com/helmfile/helmfile/releases/download/v0.155.1/helmfile_0.155.1_linux_amd64.tar.gz"
        tar xvf helmfile_0.155.1_linux_amd64.tar.gz
        sudo mv helmfile /usr/local/bin/

    - name: helmfile lint
      run: |-
        cd ./deploy && EMBED_IMAGE_REPOSITORY=embed:latest helmfile lint


